### ISSUE TITLE
Bug, something pops up for a moment

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#11] opened 2023-03-27 20:21 UTC
almost always
https://user-images.githubusercontent.com/113500363/228058507-8c1d4025-7a00-4e1c-8e92-18417e13e349.mp4

unpleasant

**Comment by NimaKhajehpour** [comment] 2023-03-27 20:29
yes that is the prompt that will pop up for any day that is empty. it asks you if you want to delete the entry for the day that is empty and has no effects. although i can not reproduce the effect that you are having on the app. maybe tell me what steps do you take to produce the effect so that i can reproduce it.

**Comment by NimaKhajehpour** [comment] 2023-03-27 20:35
ok i know what is happening now. i will fix it and re-release the version

**Comment by NimaKhajehpour** [comment] 2023-03-27 21:00
@Wjxfi the problem is fixed now, if you are going to install this re-release make sure to export your data first so that it will not get deleted and then install and re import the data

**Comment by NimaKhajehpour** [comment] 2023-03-28 03:25
yeah it is the same problem as before but its because of how the libraries are in alpha and are not complete yet. i just changed it so that the dialog would not be irritable. for popping up it is not fixable yet.

**Closed as completed** 2023-04-15 13:34 UTC
Labels: bug
