### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [NimaKhajehpour/MyMood#15] opened 2023-04-04 13:25 UTC
ref: https://monitor.f-droid.org/builds/log/com.nima.mymood/3#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/132b3825ef4f2abcefa25664faa7118f992f5730

**Comment by NimaKhajehpour** [comment] 2023-04-04 19:48
Yeah i just saw the monitor and it was a little confusing to me. I changed some settings on kotlin version and kotlin compiler version because of migration to a newer version of the material 3 library. But i dont see why that would be a problem. Do you have any idea why is it failing the rb?
Thanks for the issue and letting me know btw ❤️

**Comment by NimaKhajehpour** [comment] 2023-04-04 19:58
Yeah i just saw the monitor and it was a little confusing to me. I changed some settings on kotlin version and kotlin compiler version because of migration to a newer version of the material 3 library. But i dont see why that would be a problem. Do you have any idea why is it failing the rb?
Thanks for the issue and letting me know btw ❤️

Edit: just remembered that we had this problem with some other apps aswell. And the solution was to change the min jdk version in gradle to 18 instead of 11. Do you think that would work?

**Comment by licaon-kter** [comment] 2023-04-05 08:03
@NimaKhajehpour you mean here? https://github.com/NimaKhajehpour/MyMood/blob/master/app/build.gradle#L58-L59

We have Java17 from Debian, but not 18 yet.

**Comment by NimaKhajehpour** [comment] 2023-04-05 10:16
Yeah that was my mistake. The solution was to change java from 1.8 to 11 which is done here. So if that is not the solution what is wrong? Do you have any idea?

**Comment by licaon-kter** [comment] 2023-04-05 10:36
Unfortunately it's over my head :(

**Comment by NimaKhajehpour** [comment] 2023-04-05 10:43
Thank you for letting me know about the rb problem any way ❤️ I will try my best to figure it out asap. Let me know if you or anyone else have any idea why this is happening.

**Comment by NimaKhajehpour** [comment] 2023-04-05 12:27
@licaon-kter So i think it would be good if i had a way to see the diff on the baseline and classes 2 file and see what is different there. do you think you can provide me the diffs? also what is others opinion on this problem do they have any idea?

**Comment by licaon-kter** [comment] 2023-04-05 15:00
Sure:  [mymood3_diff.log](https://github.com/NimaKhajehpour/MyMood/files/11160238/mymood3_diff.log)

**Comment by NimaKhajehpour** [comment] 2023-04-05 15:09
thanks for the log :heart:

**Comment by NimaKhajehpour** [comment] 2023-04-05 15:16
Looking at the diff log, the only changes it has is in one of my screens and how the navigation works in it, but it should not be different since everything is the same. for example it said that one of my imports was removed but it clearly exists in my source code. as for other things on that screen. so it is really really weird that the rb has failed

**Comment by NimaKhajehpour** [comment] 2023-04-06 08:45
@licaon-kter still no idea why it would fail?

**Comment by NimaKhajehpour** [comment] 2023-04-07 18:49
@licaon-kter so there is a theory that may be the answer to this mess. i had the release 1.2.0 with another commit (the commit before this last one to be exact) and i had to change one thing in one of my screens and re-released the app to the same tag (1.2.0) name but a different commit. can it be so that the commit on YAML file was the old one when it was trying to build and comparing for the RB was done with the latest update from latest commit?

**Comment by licaon-kter** [comment] 2023-04-07 20:03
You can see which commit we use: https://gitlab.com/fdroid/fdroiddata/-/commit/132b3825ef4f2abcefa25664faa7118f992f5730

**Comment by NimaKhajehpour** [comment] 2023-04-07 20:05
yeah i just realized that but the only thing that made a little sense to me was that so now back to square one of finding out why it happened :(

**Comment by NimaKhajehpour** [comment] 2023-04-08 04:08
@licaon-kter quick question. On the pipeline there are two jobs for this commit on that has job successful and passed everything and says:

> APK file was successfully validated

and another one that actually failed the deploy. What is the first one that could build and validate the apk? Are these two completely different things?

**Comment by NimaKhajehpour** [comment] 2023-04-08 04:11
Sorry for asking all of these ridiculous questions, i know you are busy I'm just really confused why the  build would fail :(

**Comment by licaon-kter** [comment] 2023-04-08 04:24
The Gitlab CI is just used to verify merge requests and checkupdate results. It storage and processing limits, so it often uses up all it's space or takes too long and hits the 3h timeout. The Checkupdate job batches multiple apps, hence you might see some succeed and the last one failed.

The main server has higher storage/cpu limits and has a longer timeout. Also, it runs each app build in a fresh clean VM.

**Comment by NimaKhajehpour** [comment] 2023-04-08 04:41
Ok gotcha so doesn't have anything to do with what happened. Back to square one again :(

**Comment by NimaKhajehpour** [comment] 2023-04-09 15:26
@licaon-kter so what is the suggestion in this situation? what should we do? do you think we should seek help from others and see what they think about it?

**Comment by NimaKhajehpour** [comment] 2023-04-19 08:53
@licaon-kter so i decided to release a maintenance release and see if that one builds with RB, if that one is fine then we can ignore this build on fdroid. hopefully the other build does not fail

**Comment by licaon-kter** [comment] 2023-04-19 09:05
ping when ready, so we can check

**Comment by NimaKhajehpour** [comment] 2023-04-19 09:43
@licaon-kter the new release is ready to go, fingers crossed it would build with RB

**Comment by licaon-kter** [comment] 2023-04-19 11:15
trying now locally

> Exported data from database is changed so importing the data from old version of the app (versions before v.1.2.0) is impossible 

Hmm, F-Droid never had 1.2.0 so... what are users going to see?

**Comment by NimaKhajehpour** [comment] 2023-04-19 11:17
they will see old version of the app they wont see before 1.2.0 because this update is the first update that has the change on export schema

**Comment by licaon-kter** [comment] 2023-04-19 11:40
Kinda the same differences :( https://gitlab.com/-/snippets/2530022 in 1.2.1 too 

And baseline.profm too https://f-droid.org/docs/Reproducible_Builds/#potential-sources-of-unreproducible-builds

**Comment by licaon-kter** [comment] 2023-04-19 12:05
Yes, default Debian Bullseye is Java11

**Comment by NimaKhajehpour** [comment] 2023-04-19 12:10
well now we know it is not from jdk version nor diffs on code because i got a fresh build with the latest changes on the code. so the only thing might be the changes on `build.gradle` file, which again is not event close to what we see on diff log.

**Comment by NimaKhajehpour** [comment] 2023-04-21 09:12
@licaon-kter do you think the problem is caused by compilers and thats why the diffs are produced. is there any known issue with kotlin 1.8.0 or kotlin compiler 1.4.0?

**Comment by linsui** [comment] 2023-04-21 11:05
What's your build environment? JDK 11 on Linux?

**Comment by NimaKhajehpour** [comment] 2023-04-21 11:11
hey there, yeah it is open jdk 11 on arch

**Comment by NimaKhajehpour** [comment] 2023-04-29 03:52
@linsui still no idea on why it is failing the rb?

**Comment by linsui** [comment] 2023-04-29 06:09
We build the apk on Debian but this shouldn't cause problems... Did you build the apk with AS? If so, could you please try build it from command line?

**Comment by NimaKhajehpour** [comment] 2023-04-29 06:42
Yes the app is built with AS but i can try with command line. But before we did not have to build it with command line and there was no problem

**Comment by linsui** [comment] 2023-04-29 06:53
Sometimes AS has strange behavior. So maybe it's the reason. I can only guess.

**Comment by NimaKhajehpour** [comment] 2023-05-05 10:41
@linsui i have built a new release (`v1.2.2`) with command line and signed it with `apksigner`. hopefully this resolves the problem.

**Comment by licaon-kter** [comment] 2023-05-05 11:21
testing locally...

**Comment by licaon-kter** [comment] 2023-05-05 11:41
Nope:
```
--- app-release/smali_classes2/com/nima/mymood/DaggerApp_HiltComponents_SingletonC.smali        2023-05-05 11:37:09.388992481 +0000
+++ app-release-unsigned/smali_classes2/com/nima/mymood/DaggerApp_HiltComponents_SingletonC.smali       2023-05-05 11:37:17.452975784 +0000
@@ -6,7 +6,6 @@
 # annotations
 .annotation system Ldalvik/annotation/MemberClasses;
     value = {
-        Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$Builder;,
         Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$SingletonCImpl;,
         Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$ServiceCImpl;,
         Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$ActivityRetainedCImpl;,
@@ -21,7 +20,8 @@
         Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$ViewWithFragmentCBuilder;,
         Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$FragmentCBuilder;,
         Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$ActivityCBuilder;,
-        Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$ActivityRetainedCBuilder;
+        Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$ActivityRetainedCBuilder;,
+        Lcom/nima/mymood/DaggerApp_HiltComponents_SingletonC$Builder;
     }
 .end annotation
 
diff -ru app-release/smali_classes2/com/nima/mymood/database/MoodDao_Impl$10.smali app-release-unsigned/smali_classes2/com/nima/mymood/database/MoodDao_Impl$10.smali
--- app-release/smali_classes2/com/nima/mymood/database/MoodDao_Impl$10.smali   2023-05-05 11:37:09.400992456 +0000
+++ app-release-unsigned/smali_classes2/com/nima/mymood/database/MoodDao_Impl$10.smali  2023-05-05 11:37:17.464975759 +0000
@@ -46,12 +46,6 @@
         }
     .end annotation
 
-    .annotation system Ldalvik/annotation/Signature;
-        value = {
-            "()V"
-        }
-    .end annotation
-
     .line 206
     iput-object p1, p0, Lcom/nima/mymood/database/MoodDao_Impl$10;->this$0:Lcom/nima/mymood/database/MoodDao_Impl;

....10 more of these
```

**Comment by linsui** [comment] 2023-05-05 11:45
```
-    .annotation system Ldalvik/annotation/Signature;
-        value = {
-            "()V"
-        }
-    .end annotation
```

This looks familiar. It's usually caused by different jdk versions.

**Comment by licaon-kter** [comment] 2023-05-05 11:56
@linsui ok, let me retry them

**Comment by NimaKhajehpour** [comment] 2023-05-05 12:29
Thanks @licaon-kter and @linsui for helping through solving the problem 😀
Another lesson taken, dont build with AS and use command line as much as possible. Thank you for your help and patience through resolving this issue.

**Comment by licaon-kter** [comment] 2023-05-05 12:55
Updated docs: https://gitlab.com/fdroid/fdroid-website/-/commit/cf5be1e08f8522bf8d3cc0aa83e2b24fe59b6b70

**Comment by licaon-kter** [comment] 2023-05-25 13:01
Another fail: https://gitlab.com/fdroid/fdroiddata/-/jobs/4349639620#L1372

CI APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/4349639620/artifacts/file/tmp/com.nima.mymood_7.apk

Diff: [nima7.log](https://github.com/NimaKhajehpour/MyMood/files/11565079/nima7.log)

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:13
the thing is that the CI APK is not even installing on any of my devices, although my own APK installs easily

**Comment by licaon-kter** [comment] 2023-05-25 13:19
> is the CI APK signed?

No

We don't care about that now though :)

APK is not repro locally in my test now either so it's not a CI issue

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:20
another thing on the YAML i dont see the version 1.2.3 either. there is one more update that i released but it is not in the YAML

**Comment by licaon-kter** [comment] 2023-05-25 13:21
The checkupdate job keeps only the latest.

You want me to test that too?

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:21
> No

well it is not even installable. the app fails to install on any device which should not happen

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:22
> You want me to test that too? 

well it is an update that could go to fdroid i dont know if that fails or not.

**Comment by licaon-kter** [comment] 2023-05-25 13:22
> well it is not even installable. 

Yes, as expected, F-Droid builds and signs the APKs in the main server, the CI is for verifications etc.

> well it is an update that could go to fdroid i dont know if that fails or not.

testing now

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:25
so the main thing is that why we get the same error as the last version. on the last version we built the app with console and it fixed it but the problem seems to persist even if the app is built with console and directly from gradle

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:34
thats weird. so what could make it fail this version

**Comment by linsui** [comment] 2023-05-25 13:53
Maybe you can rebuild 1.2.3 and 1.3.0 and check if they are changed.

**Comment by NimaKhajehpour** [comment] 2023-05-25 13:56
well i am testing both builds from github and my local build and it does confirm with the latest changes. the build 1.2.3 does not have any problem so i wont be rebuilding it but for v1.3.0 i will re-release the app on github as the same tag to see if it has any unnoticed changes.

**Comment by NimaKhajehpour** [comment] 2023-05-25 14:08
i re-built v1.3.0 and uploaded it on the same tag as app-release.apk. but i dont think that would make any differences.

**Comment by NimaKhajehpour** [comment] 2023-05-25 14:23
done

**Comment by linsui** [comment] 2023-05-25 14:34
So the code changes causes this problem. Maybe we need to do a bisect...

**Comment by NimaKhajehpour** [comment] 2023-05-25 14:36
and what should we do exactly :thinking:

**Comment by NimaKhajehpour** [comment] 2023-05-25 15:34
so i did a bisect from last version to this one and i did not see anything that might have caused the issue. although i might just dont know what to look for. i did a git diff of two heads too so i can see where i might have had the problem but again nothing. maybe i did not know what to look at, feel free to tell me what to do more and i will try them. :worried:

**Comment by NimaKhajehpour** [comment] 2023-05-25 16:44
yeah i guess that would be a good way to find the bad commit. so where would i upload the build. should i put it on a separate tag and delete it at the end?

**Comment by NimaKhajehpour** [comment] 2023-05-26 09:37
bisect commits are:
3d08a558: [app-release-c3d08a558.zip](https://github.com/NimaKhajehpour/MyMood/files/11573721/app-release-c3d08a558.zip)
3438b0bc: [app-release-c3438b0bc.zip](https://github.com/NimaKhajehpour/MyMood/files/11573739/app-release-c3438b0bc.zip)
a1755b6c: [app-release-ca1755b6c.zip](https://github.com/NimaKhajehpour/MyMood/files/11573749/app-release-ca1755b6c.zip)

**Comment by licaon-kter** [comment] 2023-05-26 09:53
I'm rebuilding each and will compare

**Comment by licaon-kter** [comment] 2023-05-26 10:37
[mymood_a1755b6c.log](https://github.com/NimaKhajehpour/MyMood/files/11574297/mymood_a1755b6c.log) - > not repro

https://github.com/NimaKhajehpour/MyMood/commit/3438b0bc9fe3a03e2e8af82483ae33d6a489fd36 -> repro

[mymood_3d08a558.log](https://github.com/NimaKhajehpour/MyMood/files/11574301/mymood_3d08a558.log) -> not repro

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:01
this is a weird thing because the reproducible release has all the changes from commit a1755b6 and the other non-reproducible app does not have a lot of changes since the reproducible one. shouldn't it be so that if the parent commit is not repro the child commit should not be repro either?

**Comment by linsui** [comment] 2023-05-26 11:03
Maybe the build is not deterministic.

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:05
so what does that mean?

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:14
@linsui one thing, do you remember that one time i was building with jdk 11 and the reproducibility got fixed when i changed gradle compatibility from jdk 8 to jdk 11? now i am building with jdk 17 and i have gradle compat on jdk 11, i know obfusk said it does not have anything to do with the problem but do you think we should try that?

**Comment by linsui** [comment] 2023-05-26 11:19
I guess we can have a try.

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:30
release for the latest commit for compatibility changes on gradle. fingers crossed
[app-release-latest-changes.zip](https://github.com/NimaKhajehpour/MyMood/files/11574703/app-release-latest-changes.zip)

**Comment by linsui** [comment] 2023-05-26 11:33
Let me have a try. :)

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:47
as for the build not being deterministic i am using gradle com.android.application version 7.3.1 and invoking assemble release directly from gradlew, zipalign and the sign it with apksigner. are the steps correct or should i remove zip aligning step?

**Comment by linsui** [comment] 2023-05-26 11:48
It works! Do you have jdk 11 installed on your system?

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:49
yeah i have openjdk 11 and openjdk 17 but my console default is openjdk 17 which is used when i build without AS

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:51
> It works!
so is the app reproducible with the change we made?

**Comment by linsui** [comment] 2023-05-26 11:55
Yes, with the change it's reproducible. I guess the jdk 11 is used in some steps somehow.

**Comment by NimaKhajehpour** [comment] 2023-05-26 11:57
can that be because of the jvm target on gradle? i changed that too, it should not make a difference since i am specifically building with openjdk 17 but it seems like even building with console is not completely consistent on the versions

**Comment by linsui** [comment] 2023-05-26 11:58
Maybe you can test that by removing jdk 11 and rebuild the apk without the latest change.

**Comment by NimaKhajehpour** [comment] 2023-05-26 12:00
yeah good call. i will remove jdk 11 and revert the changes.

**Comment by linsui** [comment] 2023-05-26 12:17
It's reproducible. So the problem is that jdk 11 is used somehow...

**Comment by linsui** [comment] 2023-05-26 12:21
Thanks!

**Comment by NimaKhajehpour** [comment] 2023-05-26 12:25
shall we close the issue?

**Comment by linsui** [comment] 2023-05-26 12:40
Yes, I have [re-enabled](https://gitlab.com/fdroid/fdroiddata/-/commit/e2d48c95aee417140cc77a2bfd1b449b600370f7) 1.3.0. Thanks!

**Closed** 2023-05-26 12:41 UTC
Labels: help wanted
