### ISSUE TITLE
the ability to edit my notes

### ISSUE THREAD

**Issue by Wjxfi** [NimaKhajehpour/MyMood#16] opened 2023-04-15 13:34 UTC
a long press will have an "edit" button in addition to deletion

**Comment by angel-721** [comment] 2023-04-29 02:40
I can try adding this! I'm not sure if I'll do a long press but I might do something like add a edit button on every note so you can go back and edit them.

**Comment by NimaKhajehpour** [comment] 2023-04-29 03:01
Hey there, thanks for the offer. Right now the problem is not adding the features. The biggest problem is the RB on fdroid that stopps my progress on updating the app for now 😕

**Comment by angel-721** [comment] 2023-04-29 03:17
I hope that can get resolved soon :pray: . For the time would it be alright if I can implement this feature so that once the fdroid problems get resolved it can be pushed to it?

**Comment by NimaKhajehpour** [comment] 2023-04-29 03:26
Well if you know kotlin and jetpack compose then yes it would be helpful. I might just take a look at it and make sure everything is all right but other than that it sounds good. ❤️

**Comment by angel-721** [comment] 2023-04-29 04:19
Sounds great! I'll link a PR to this issue once it's ready! I'm going to approach this by adding a update function that activates on a double tap that navigates to the screen to edit the tapped effect!

**Comment by NimaKhajehpour** [comment] 2023-04-29 04:36
You can either do this or if you want to make it easier for you and the user to have the least amount of navigations and screens you can easily add a dialog or bottom sheet that has an edit text that lets you enter new value.
But either way if you are adding a navigatiin and screen make sure you add the screen to tthe enum `Screens`. Good luck with adding the feature 😀

**Comment by NimaKhajehpour** [comment] 2023-04-29 04:37
In android it is important to make your app easy to use and have less navigations if possible

**Comment by angel-721** [comment] 2023-04-29 06:45
You're right! I got the basics of being able to edit the effect description down. Right now it only works on the HomeScreen but I'll add it to every screen where it's appropriate. Changes can be seen here:https://github.com/angel-721/MyMood/tree/edit-notes. I can also try to add changing the mood(rate) or maybe it's best to get the effect description down first? Thank you so much for your kindness and being open! 

Below is a preview of the changes:


https://user-images.githubusercontent.com/75283919/235287991-3adf16c6-6118-4f69-8a5f-adbaf311f8ac.mp4



So far I choose to approach this similar to delete by adding a boolean to every screen that changes on a doubleTap. This boolean will cause an alert similar to the delete to open but I added some DAO, repository, and viewModel methods to update the description of a effect and it will cause those methods if the user presses confirm.

**Comment by NimaKhajehpour** [comment] 2023-04-29 06:58
Sadly the video doesn't open. I will look at the code and the video once i get home. Bit thanks for helping to improve the app. And don't worry about being open this app is improving only because of users like you

**Comment by NimaKhajehpour** [comment] 2023-04-29 07:09
Still unable to download

**Comment by NimaKhajehpour** [comment] 2023-04-29 12:07
@angel-721 the code and actions you described looks pretty good to me. Your approach helps the app to have simillar to deleting the effect which keeps the app user friendly. Also we have to make sure ui tells the user that the feature is available by double tapping. So i was thinking about adding a tooltip the time app opens to inform tje user, or add a text to assure user that tbe feature is always there to use. Its your call which one to add. Or if it is too much i can add it myself at some other time 😉
Either way thanks again for helping improve the app.
Happy coding ❤️

**Comment by angel-721** [comment] 2023-04-29 14:14
Right now on every effectListItem in the UI I added a text that starts with a newline so it goes under the "long press to delete" and it's "double tap to edit". I'll make sure to add this to the tooltip and make sure it can be used in every state! Right now I'll focus on on effect description and make sure that is working before moving on to rate! :heart:

**Comment by NimaKhajehpour** [comment] 2023-04-29 14:23
I think having either one of the text or tooltip is enough. An idea for adding the edit rate is that to simply implement that on the same dialog and make editting the effect easier by letting user do everything at once. Good luck. Let me know whenever you need any help at any stage 😉

**Comment by angel-721** [comment] 2023-04-30 02:32
Just submitted a PR for being able to update the description alone of a effect. I made sure to add in the UI a text field the same where there is one for long pressing to delete, I added  one to let users know to double tap to edit. Just descriptions for now. I might work on rates later.

**Comment by NimaKhajehpour** [comment] 2023-04-30 04:49
Hey thanks for adding the feature. It looks gopd to me 😀 although i have to wait a little to merge your pr. I have to see one thing before changing the code. Once that is done pr will be merged. Again thank you for doing this❤️

**Comment by NimaKhajehpour** [comment] 2023-05-06 14:02
Hey there, yreah so the rb test just got success on fdroid so i will be restating the updates asap when I get free time to do so which probably will be at Wednesday.

**Closed as completed** 2023-05-24 16:58 UTC
